### ISSUE TITLE
php error inside bin/receiving-dock.sh

### ISSUE THREAD

**Issue by fredzannarbor** [fredzannarbor/pagekicker-community#18]
Probably occurring because magento is not running while receiving dock is trying to get it to import -- verify

```
lifting the boxes off the truck and putting them on the conveyor belt

PHP Fatal error:  Uncaught exception 'Zend_Db_Adapter_Exception' with message 'pdo_mysql extension is not installed' in /home/fred/bin/magento-1.9.2.4-1/apps/magento/htdocs/lib/Varien/Db/Adapter/Pdo/Mysql.php:372
Stack trace:
#0 /home/fred/bin/magento-1.9.2.4-1/apps/magento/htdocs/lib/Zend/Db/Adapter/Abstract.php(460): Varien_Db_Adapter_Pdo_Mysql->_connect()
#1 /home/fred/bin/magento-1.9.2.4-1/apps/magento/htdocs/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SET NAMES utf8', Array)
#2 /home/fred/bin/magento-1.9.2.4-1/apps/magento/htdocs/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('SET NAMES utf8', Array)
#3 /home/fred/bin/magento-1.9.2.4-1/apps/magento/htdocs/app/code/core/Mage/Core/Model/Resource.php(179): Varien_Db_Adapter_Pdo_Mysql->query('SET NAMES utf8')
#4 /home/fred/bin/magento-1.9.2.4-1/apps/magento/htdocs/app/code/core/Mage/Core/Model/Resource.php(110): Mage_Core_Model_Resource->_newConnection('pdo_mysql', Object(Mage_Core_Model_Config_Element))
#5 /home/ in /home/fred/bin/magento-1.9.2.4-1/apps/magento/htdocs/lib/Varien/Db/Adapter/Pdo/Mysql.php on line 372

```

**Comment by fredzannarbor** [comment]
only occurs if magento cron import php is missing (custom program on PK demo site)
